### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by emanuelstanciu** [snt/dump1090mqtt#1]
Note sure if you are still working on this or if you remember what's happening, I found your script by searching for an MQTT solution for ADS-B.
I configure everything, but when I try to run the script I get:

  File "./dump1090mqtt.py", line 48, in <module>
    topic = "/adsb/%s/%s" % (RADAR, xs[4])
IndexError: list index out of range

Any ideas?

**Comment by snt** [comment]
Please make sure `dump1090pub.py` listens to correct port of `dump1090` by trying this: `nc 127.0.0.1 30003`, assuming your `dump1090` is running on same host(`127.0.0.1`) and port is default, `30003`.  You should get some thing like this:

```
$ nc 127.0.0.1 30003
MSG,7,111,11111,86D30F,111111,2015/06/02,20:08:59.213,2015/06/02,20:08:59.213,,26975,,,,,,,,,,0
MSG,5,111,11111,861E78,111111,2015/06/02,20:08:59.408,2015/06/02,20:08:59.408,,29000,,,,,,,0,,0,0
...
```

On line 47 of the code, each line is split with `,` so `xs[4]` of line 48 is `86D30F` for the first line of the above `nc` output, for example.
`IndexError: list index out of range` means `xs[4]` does not exist maybe because it reads something in a format other than CSV above.

**Comment by emanuelstanciu** [comment]
perfect, I think I had the port wrongly set up, my plotter uses 30005 and I thought that will work.. set it back to the default and everything works fine.. great little script, thanks
